[project]
name = 'xyra_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.data_storage]
path = 'contracts/data_storage.clar'
clarity_version = 2
epoch = 2.5

[contracts.research_funds]
path = 'contracts/research_funds.clar'
clarity_version = 2
epoch = 2.5

[contracts.ressss]
path = 'contracts/ressss.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
